language: rust

rust:
  - 1.0.0-beta.2
  - nightly

install:
  - sudo apt-get update -qq
  - sudo apt-get install libxxf86vm-dev libosmesa6-dev
  - ./travis-install-assimp.sh

before_script:
  - rustc -V
  - cargo -V

script:
  - cargo build -v
  - cargo test -v
  - cargo test -v -p assimp-sys
